server:
  port: 9966

spring:
  messages.basename: messages/messages
  datasource:
    schema: classpath*:db/hsqldb/schema.sql
    data: classpath*:db/hsqldb/data.sql
    url: jdbc:hsqldb:mem:petclinic
    username: admin
    password: admin
  jpa:
    database: HSQL
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: none

logging.level.org.springframework: INFO
